### ISSUE TITLE
任务分发异常

### ISSUE THREAD

**Issue by planet-xuhao** [lanslot-moon/KafkaSortMsgConsumer#1]
public SingleThreadWorker(int size) {
        this.queue = new LinkedBlockingQueue<>(size);
        this.queueNo = cnt.getAndIncrement();
        log.info("init worker {}", this.queueNo);
    }

这个cnt在初始化时会+1，但只在此处执行一次，如果是多个任务并行处理，那么同组的cnt应该是不同的

**Comment by lanslot-moon** [comment]
cnt为static修饰的字段，随着类的加载而加载出来，且只加载一次，多次实例后cnt会进行递增
